name: flutter_admin_app
description: A comprehensive admin application for business management

# Prevent accidental publishing
publish_to: 'none'

# Version management
version: 1.0.0+1

# SDK and Flutter version constraints
environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  # Flutter core
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.4

  # Networking
  http: ^1.1.0
  dio: ^5.4.1
  connectivity_plus: ^5.0.2
  http_parser: ^4.0.2
  path: ^1.8.3

  # Local Storage and Preferences
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  flutter_secure_storage: ^9.0.0

  # Image Handling
  image_picker: ^1.0.4
  photo_view: ^0.14.0
  image: ^4.1.3
  image_cropper: ^5.0.1

  # Data Visualization
  fl_chart: ^0.63.0
  
  # Internationalization
  intl: ^0.18.1
  timezone: ^0.9.2

  # Utilities
  json_annotation: ^4.8.0
  google_fonts: ^5.1.0

  # Notifications
  flutter_local_notifications: ^16.3.3

  # PDF and Excel Export
  pdf: ^3.10.4
  excel: ^2.1.0
  open_file: ^3.3.2

  # Routing
  go_router: ^12.1.1

  # JSON Serialization
  json_serializable: ^6.7.0

  # Logging
  get_it: ^7.6.0
  
  # URL handling and sharing
  url_launcher: ^6.2.5
  share_plus: ^7.2.1
  
  # Permissions
  permission_handler: ^11.2.0

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.0
  
  # State Management Testing
  bloc_test: 9.1.7
  
  # Mocking
  mocktail: ^1.0.0

  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/logo.jpg"

flutter:
  # Enable Material Design
  uses-material-design: true
  
  # Enable localization
  generate: true

  # Asset configurations
  assets:
    - assets/images/
    - assets/images/icons/logo.jpg
    - assets/images/icons/cash.png
    - assets/images/icons/transfer.png
    - assets/images/icons/e-wallet.png
    - assets/fonts/
    - assets/translations/

  # Font configurations
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic

    - family: Icons
      fonts:
        - asset: assets/fonts/custom_icons.ttf

# Dependency overrides (if needed)
dependency_overrides:
  intl: ^0.18.1

# Additional configuration notes
# Run these commands to manage dependencies:
# - flutter pub get
# - flutter pub upgrade
# - flutter pub outdated